#pragma once
#define DRIVER_PREFIX "Nastyware MiniFilter: "

typedef struct _NASTYWARE_FEEDBACK_ {
	BOOLEAN Malware;
} NASTYWARE_FEEDBACK, *PNASTYWARE_FEEDBACK;

typedef struct _NASTYWARE_MESSAGE_ {
	USHORT	Length;
	WCHAR	FileName[4096];
} NASTYWARE_MESSAGE, *PNASTYWARE_MESSAGE;

typedef struct _NASTYWARE_REPLY_MESSAGE_ {
	FILTER_REPLY_HEADER ReplyHeader;
	NASTYWARE_FEEDBACK Feedback;
} NASTYWARE_REPLY_MESSAGE, *PNASTYWARE_REPLY_MESSAGE;